
export interface Ingredient {
  id: string;
  name: string;
  category: string;
  price: number;
  description?: string;
}

export const INGREDIENTS_DB: Ingredient[] = [
  // Proteins
  { id: 'p1', name: 'Collagen Peptides', category: 'Proteins', price: 203.28 },
  { id: 'p2', name: 'Hemp Protein', category: 'Proteins', price: 0.00 },
  { id: 'p3', name: 'Vegan Rice Protein', category: 'Proteins', price: 0.00 },
  { id: 'p4', name: 'Whey Hydrolysate', category: 'Proteins', price: 0.00 },
  { id: 'p5', name: 'Whey Protein Concentrate (Grass Fed)', category: 'Proteins', price: 0.00 },
  { id: 'p6', name: 'Whey Protein Isolate', category: 'Proteins', price: 0.00 },
  
  // Carbohydrates
  { id: 'c1', name: 'Agenanova®', category: 'Carbohydrates', price: 106.38 },
  { id: 'c2', name: 'D-Ribose', category: 'Carbohydrates', price: 196.29 },
  { id: 'c3', name: 'Fructose', category: 'Carbohydrates', price: 46.62 },
  { id: 'c4', name: 'Maltodextrin', category: 'Carbohydrates', price: 58.89 },
  { id: 'c5', name: 'Palatinose®', category: 'Carbohydrates', price: 81.89 },

  // Fats & Fatty Acids
  { id: 'f1', name: 'CLA (60%)', category: 'Fats', price: 124.67 },
  { id: 'f2', name: 'Exogenous Ketones (ß-Hydroxybutyrate)', category: 'Fats', price: 264.51 },
  { id: 'f3', name: 'MCT (Oil)', category: 'Fats', price: 0.00 },
  { id: 'f4', name: 'MCT Powder', category: 'Fats', price: 301.26 },

  // Amino Acids
  { id: 'aa1', name: 'Essential Amino Acid Blend', category: 'Amino Acids', price: 153.93 },
  { id: 'aa2', name: 'BCAA Blend', category: 'Amino Acids', price: 92.98 },
  { id: 'aa3', name: 'Betaine', category: 'Amino Acids', price: 34.10 },
  { id: 'aa4', name: 'Glycine', category: 'Amino Acids', price: 80.59 },
  { id: 'aa5', name: 'L-Arginine', category: 'Amino Acids', price: 89.52 },
  { id: 'aa6', name: 'L-Arginine AKG', category: 'Amino Acids', price: 133.12 },
  { id: 'aa7', name: 'L-Carnitine', category: 'Amino Acids', price: 78.56 },
  { id: 'aa8', name: 'L-Glutamine', category: 'Amino Acids', price: 72.58 },
  { id: 'aa9', name: 'L-Histidine HCL', category: 'Amino Acids', price: 33.94 },
  { id: 'aa10', name: 'L-Isoleucine', category: 'Amino Acids', price: 122.25 },
  { id: 'aa11', name: 'L-Leucine', category: 'Amino Acids', price: 87.50 },
  { id: 'aa12', name: 'L-Lysine', category: 'Amino Acids', price: 148.38 },
  { id: 'aa13', name: 'L-Methionine', category: 'Amino Acids', price: 17.14 },
  { id: 'aa14', name: 'L-Phenylalanine', category: 'Amino Acids', price: 20.09 },
  { id: 'aa15', name: 'L-Theanine', category: 'Amino Acids', price: 29.26 },
  { id: 'aa16', name: 'L-Threonine', category: 'Amino Acids', price: 17.31 },
  { id: 'aa17', name: 'L-Tryptophan', category: 'Amino Acids', price: 82.73 },
  { id: 'aa18', name: 'L-Tyrosine', category: 'Amino Acids', price: 43.62 },
  { id: 'aa19', name: 'L-Valine', category: 'Amino Acids', price: 77.69 },
  { id: 'aa20', name: 'Taurine', category: 'Amino Acids', price: 30.04 },

  // Minerals
  { id: 'm1', name: 'Electrolyte Blend', category: 'Minerals', price: 43.12 },
  { id: 'm2', name: 'Mineral Blend', category: 'Minerals', price: 66.76 },
  { id: 'm3', name: 'Boron', category: 'Minerals', price: 20.53 },
  { id: 'm4', name: 'Calcium Lactate', category: 'Minerals', price: 135.82 },
  { id: 'm5', name: 'Chromium A.A.C.', category: 'Minerals', price: 9.10 },
  { id: 'm6', name: 'Copper A.A.C.', category: 'Minerals', price: 10.72 },
  { id: 'm7', name: 'Iodine (Potassium Iodide)', category: 'Minerals', price: 16.33 },
  { id: 'm8', name: 'Iron A.A.C.', category: 'Minerals', price: 23.39 },
  { id: 'm9', name: 'Magnesium Glycinate', category: 'Minerals', price: 52.61 },
  { id: 'm10', name: 'Magnesium Citrate (8.5% Element)', category: 'Minerals', price: 62.16 },
  { id: 'm11', name: 'Manganese A.A.C.', category: 'Minerals', price: 11.60 },
  { id: 'm12', name: 'Molybdenum A.A.C.', category: 'Minerals', price: 9.52 },
  { id: 'm13', name: 'Potassium Bicarbonate', category: 'Minerals', price: 34.24 },
  { id: 'm14', name: 'Selenium A.A.C.', category: 'Minerals', price: 10.70 },
  { id: 'm15', name: 'Sodium Bicarbonate', category: 'Minerals', price: 57.31 },
  { id: 'm16', name: 'Zinc A.A.C.', category: 'Minerals', price: 43.05 },

  // Vitamins
  { id: 'v1', name: 'Vitamin Blend (100% NRV)', category: 'Vitamins', price: 34.01 },
  { id: 'v2', name: 'Vitamin-B Complex', category: 'Vitamins', price: 100.49 },
  { id: 'v3', name: 'Vitamin A', category: 'Vitamins', price: 12.41 },
  { id: 'v4', name: 'Vitamin B1 (Thiamine)', category: 'Vitamins', price: 27.21 },
  { id: 'v5', name: 'Vitamin B12', category: 'Vitamins', price: 22.60 },
  { id: 'v6', name: 'Vitamin B12 (Methylcobalamin)', category: 'Vitamins', price: 10.89 },
  { id: 'v7', name: 'Vitamin B2 (Riboflavin)', category: 'Vitamins', price: 30.42 },
  { id: 'v8', name: 'Vitamin B3 (Niacin)', category: 'Vitamins', price: 10.52 },
  { id: 'v9', name: 'Vitamin B3 (Nicotinamide)', category: 'Vitamins', price: 10.92 },
  { id: 'v10', name: 'Vitamin B5 (Ca-D-Pantothenate)', category: 'Vitamins', price: 39.50 },
  { id: 'v11', name: 'Vitamin B6 (P5P)', category: 'Vitamins', price: 34.22 },
  { id: 'v12', name: 'Vitamin B7 (Biotin)', category: 'Vitamins', price: 12.76 },
  { id: 'v13', name: 'Vitamin B9 (Methylfolate)', category: 'Vitamins', price: 50.98 },
  { id: 'v14', name: 'Vitamin C', category: 'Vitamins', price: 32.31 },
  { id: 'v15', name: 'Vitamin D3', category: 'Vitamins', price: 17.88 },
  { id: 'v16', name: 'Vitamin E', category: 'Vitamins', price: 47.91 },
  { id: 'v17', name: 'Vitamin E (Tocotrienol)', category: 'Vitamins', price: 210.08 },
  { id: 'v18', name: 'Vitamin K2', category: 'Vitamins', price: 61.07 },

  // Other Nutrients
  { id: 'on1', name: 'Alpha Lipoic Acid', category: 'Other', price: 30.80 },
  { id: 'on2', name: 'Ashwagandha', category: 'Other', price: 230.51 },
  { id: 'on3', name: 'Beta Alanine', category: 'Other', price: 27.94 },
  { id: 'on4', name: 'Boswellia Serrata (65% B.A.)', category: 'Other', price: 42.92 },
  { id: 'on5', name: 'Caffeine', category: 'Other', price: 16.81 },
  { id: 'on6', name: 'Choline Bitartrate', category: 'Other', price: 33.66 },
  { id: 'on7', name: 'Co-Enzyme Q10', category: 'Other', price: 102.35 },
  { id: 'on8', name: 'Colostrum', category: 'Other', price: 193.95 },
  { id: 'on9', name: 'Creatine Monohydrate', category: 'Other', price: 141.45 },
  { id: 'on10', name: 'Curcumin C3 Complex®', category: 'Other', price: 132.45 },
  { id: 'on11', name: 'DigeZyme®', category: 'Other', price: 66.30 },
  { id: 'on12', name: 'DIM (Broccoli Extract)', category: 'Other', price: 169.94 },
  { id: 'on13', name: 'Fibersol-2®', category: 'Other', price: 136.95 },
  { id: 'on14', name: 'Fibregum B®', category: 'Other', price: 45.36 },
  { id: 'on15', name: 'FOS (Fructo-Oligosaccharides)', category: 'Other', price: 38.66 },
  { id: 'on16', name: 'Fulvic Acid', category: 'Other', price: 266.46 },
  { id: 'on17', name: 'GABA', category: 'Other', price: 32.18 },
  { id: 'on18', name: 'Ginseng (Panax)', category: 'Other', price: 87.69 },
  { id: 'on19', name: 'Glucosamine Sulfate', category: 'Other', price: 68.42 },
  { id: 'on20', name: 'Grape Seed Extract', category: 'Other', price: 21.44 },
  { id: 'on21', name: 'Green Coffee Bean Extract', category: 'Other', price: 67.58 },
  { id: 'on22', name: 'Green Tea Extract', category: 'Other', price: 29.11 },
  { id: 'on23', name: 'HMB', category: 'Other', price: 114.04 },
  { id: 'on24', name: 'Inositol', category: 'Other', price: 46.84 },
  { id: 'on25', name: 'L-Citrulline Malate', category: 'Other', price: 101.68 },
  { id: 'on26', name: 'L-Glutathione', category: 'Other', price: 366.94 },
  { id: 'on27', name: 'Milk Thistle', category: 'Other', price: 110.14 },
  { id: 'on28', name: 'MSM', category: 'Other', price: 38.63 },
  { id: 'on29', name: 'NAC (N-Acetyl-L-Cysteine)', category: 'Other', price: 43.45 },
  { id: 'on30', name: 'N-Acetyl-L-Carnitine', category: 'Other', price: 144.71 },
  { id: 'on31', name: 'NMN', category: 'Other', price: 263.22 },
  { id: 'on32', name: 'Nucleotides', category: 'Other', price: 574.49 },
  { id: 'on33', name: 'Phosphatidylserine', category: 'Other', price: 284.37 },
  { id: 'on34', name: 'Piperine', category: 'Other', price: 29.78 },
  { id: 'on35', name: 'Probiotic', category: 'Other', price: 78.79 },
  { id: 'on36', name: 'Psyllium Husk', category: 'Other', price: 124.45 },
  { id: 'on37', name: 'Quercetin', category: 'Other', price: 340.36 },
  { id: 'on38', name: 'Raspberry Ketones', category: 'Other', price: 28.27 },
  { id: 'on39', name: 'Resveratrol', category: 'Other', price: 275.21 },
  { id: 'on40', name: 'Rhodiola Rosea', category: 'Other', price: 45.10 },
  { id: 'on41', name: 'Spirulina', category: 'Other', price: 62.69 },
  { id: 'on42', name: 'Tolerase', category: 'Other', price: 52.24 },
  { id: 'on43', name: 'Wellmune®', category: 'Other', price: 223.80 },
  { id: 'on44', name: 'Bromelain', category: 'Other', price: 85.50 },
];
